<?php
/** 
 * @var string $title Page Title
 * @var string $list_route Route to this list
 * @var int $id Id of currentliy editing element
 * @var string $edit_route Route to edit entry
 * @var string $edit_param_name Parameter name for edit route. Default: id
 * @var string $delete_route Route to delete entry
 * @var string $delete_param_name Parameter name for delete route. Default: id
 * @var string $delete_warning_text Text to show before deleting
 * @var Form $form Creation form
 */

if(empty($this->delete_param_name))
	$this->delete_param_name = 'id';
if(empty($this->edit_param_name))
	$this->edit_param_name = 'id';

$routeParams = array($this->edit_param_name => $this->id);
if(!empty($this->parent_param_name))
	$routeParams = array($this->parent_param_name => $this->parent_id) + $routeParams;

$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url($edit_route, $routeParams));
$form->setAttribute('method', 'post');
?>

<h1><?php echo $this->translate($this->title) ?></h1>

<?php include 'admin_form.phtml'; ?>

<a href="<?php echo $this->url($this->delete_route, array($this->delete_param_name => $this->id)); ?>"
   onclick="return confirm('<?php echo $this->translate($this->delete_warning_text) ?>')">
    <?php echo $this->translate('Delete') ?>
</a>