<?php echo $this->doctype(); ?>

<html lang="en">
	<head>
		<meta charset="utf-8">
		<?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

		<?php echo $this->headMeta()
			->appendName('viewport', 'width=device-width, initial-scale=1.0')
			->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
		?>

		<!-- Le styles -->
		<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
				->prependStylesheet($this->basePath() . '/css/style.css')
				->prependStylesheet($this->basePath() . '/css/jquery.fs.selecter.css')
				->prependStylesheet($this->basePath() . '/css/jquery.fs.stepper.css')
				->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
				->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
		
		<!-- Scripts -->
		<?php $this->bower('main', \BowerModule\View\Helper\Bower::CONTAINER_HEAD); ?>

		<?php echo $this->headScript()->prependFile($this->basePath() . '/js/ieLT9.min.js', 'text/javascript', array('conditional' => 'lt IE 9',)); ?>
		<script type="text/javascript">
			$(function(){
				$('select').selecter();
			})
		</script>
	</head>

  <body style="padding-top: 70px;">

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url('zfcadmin') ?>">ZfcAdmin</a>
                </div>
                <div class="collapse navbar-collapse">
                    <?php echo $this->navigation('admin_navigation')
                            ->menu()
                            ->setUlClass('nav navbar-nav')
                            ->setMaxDepth(0)
                            ->setRenderInvisible(false)?>
                </div><!--/.nav-collapse -->
            </div>
        </nav>

    <div class="container">
      <?php echo $this->flashMessenger()->render(); ?>
      <?php echo $this->content; ?>

      <hr>

      <footer>
        <p>&copy; 2014</p>
      </footer>

    </div> <!-- /container -->

  <?php echo $this->inlineScript() ?>
  </body>
</html>
