<?php
/** 
 * @var string $title Page Title
 * @var string $list_route Route to this list
 * @var string $create_route Route to create new entry
 * @var string $id_name name of id property for edit/delete. Default: id
 * @var string $edit_route Route to edit entry
 * @var string $edit_param_name Parameter name for edit route. Default: id
 * @var string $delete_route Route to delete entry
 * @var string $delete_param_name Parameter name for delete route. Default: id
 * @var string $delete_warning_text Text to show before deleting
 * @var string $create_text Text on create button
 * @var array $columns Array of Columns to be displayed (Key: Display, Value: getter)
 * @var array $rows Array of Objects to be shown
 * @var int $page Page number for pagination
 * @var int $page_length Number of items on one page
 *
 * @var string $parent_list_route Route to parent List
 * @var string $parent_param_name Parent ID param in all sublist views
 * @var string $parent_id Parent ID
 */

if(empty($this->delete_param_name))
	$this->delete_param_name = 'id';
if(empty($this->edit_param_name))
	$this->edit_param_name = 'id';
if(empty($this->id_name))
	$this->id_name = 'id';

if (is_array($this->rows)) {
    $paginator = new Zend\Paginator\Paginator(new Zend\Paginator\Adapter\ArrayAdapter($this->rows));
} elseif($this->rows instanceof Traversable && !($this->rows instanceof Zend\Paginator\Paginator)) {
    $paginator = new Zend\Paginator\Paginator(new Zend\Paginator\Adapter\Iterator($this->rows));
} else {
    $paginator = $this->rows;
}

$paginator->setItemCountPerPage($this->page_length);
$paginator->setCurrentPageNumber($this->page);


$getters = array();
foreach ($this->columns as $element) {
    $parts = explode('_', $element);
    array_walk($parts, function (&$val) {
        $val = ucfirst($val);
    });
    $getters[$element] = 'get' . implode('', $parts);
}

$parts = explode('_', $this->id_name);
array_walk($parts, function (&$val) {
    $val = ucfirst($val);
});
$idGetter = 'get' . implode('', $parts);

$isSublist = false;
if(!empty($this->parent_list_route))
	$isSublist = true;

?>

<h1><?php echo $this->translate($this->title) ?></h1>

<div class="navbar filter-bar">
    <div class="navbar-inner">
        <div class="pull-right">
			<?php if(!empty($this->create_route)) : ?>
	            <a href="<?php echo $this->url($this->create_route, $isSublist ? array($this->parent_param_name => $this->parent_id) : array()) ?>" class="btn btn-primary">
	                <?php echo $this->translate($this->create_text) ?>
	            </a>
			<?php endif; ?>
        </div>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <?php foreach ($this->columns as $name => $element): ?>
                <th><?php echo $this->escapeHtml($name ? : $element); ?></th>
            <?php endforeach; ?>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($paginator as $row): ?>
        <tr>
            <?php foreach ($this->columns as $element): ?>
                <td class="cell cell-<?php echo $this->escapeHtml($element) ?>">
                    <?php 
						$value = call_user_func(array($row, $getters[$element]));
						if($value instanceof DateTime)
							$value = $value->format('Y-m-d H:i');
						echo $value;
					?>
                </td>
            <?php endforeach; ?>
            <td class="cell cell-ctrls">
				<?php
					$buttons = array();
					if(!empty($this->row_buttons)){
						foreach($this->row_buttons as $button){
							$routeParams = $isSublist ? array($this->parent_param_name => $this->parent_id) : array();
							$routeParams[$button['param_name']] = call_user_func(array($row, $idGetter));
							
							if($isSublist && !empty($this->parent_alias))
								$routeParams = array('alias' => $this->parent_alias) + $routeParams;
							
							if(!empty($this->item_alias_name) && method_exists($row, 'getAlias'))
								$routeParams = array($this->item_alias_name => $row->getAlias()) + $routeParams;
							
							if(empty($button['more_params']))
								$button['more_params'] = array();
							
							$buttons[] = array(
								'title' => $button['title'],
								'route' => $button['route'],
								'params' => $button['more_params'] + $routeParams
							);
						}
					}
					
					if(!empty($this->sublist_route)){
						$routeParams = array($this->parent_param_name => call_user_func(array($row, $idGetter)) );
						if(!empty($this->item_alias_name) && method_exists($row, 'getAlias'))
							$routeParams = array($this->item_alias_name => $row->getAlias()) + $routeParams;
						
						$buttons[] = array(
							'title' => $this->sublist_link_name,
							'route' => $this->sublist_route,
							'params' => $routeParams
						);
					}
					
					if(!empty($this->edit_route)){
						$routeParams = $isSublist ? array($this->parent_param_name => $this->parent_id) : array();
						$routeParams[$this->edit_param_name] = call_user_func(array($row, $idGetter));
						if($isSublist && !empty($this->parent_alias))
							$routeParams = array('alias' => $this->parent_alias) + $routeParams;
						
						if(!empty($this->item_alias_name) && method_exists($row, 'getAlias'))
							$routeParams = array($this->item_alias_name => $row->getAlias()) + $routeParams;
						
						$buttons[] = array(
							'title' => "Edit",
							'route' => $this->edit_route,
							'params' => $routeParams
						);
					}

					if(!empty($this->delete_route)){
						$routeParams = $isSublist ? array($this->parent_param_name => $this->parent_id) : array();
						$routeParams[$this->delete_param_name] = call_user_func(array($row, $idGetter));
						if($isSublist && !empty($this->parent_alias))
							$routeParams = array('alias' => $this->parent_alias) + $routeParams;
						
						if(!empty($this->item_alias_name) && method_exists($row, 'getAlias'))
							$routeParams = array($this->item_alias_name => $row->getAlias()) + $routeParams;
						
						$buttons[] = array(
							'title' => "Delete",
							'route' => $this->delete_route,
							'params' => $routeParams,
							'warning' => $this->delete_warning_text
						);
					}
				?>
				<?php $c = 0;?>
				<?php foreach($buttons as $button): ?>
					<?= $c == 0 ? '' : '|'  ?>
					<a href="<?php echo $this->url($button['route'], $button['params']); ?>" <?= empty($button['warning']) ? '' : 'onclick=" return confirm(\''.$button['warning'].'\')"' ?> >
						<?php echo $this->translate($button['title']) ?>
					</a>
					<?php $c++; ?>
				<?php endforeach; ?>
            </td>
        </tr>
		<tr><td colspan="<?php echo count($this->columns) + 1; ?>" class="eventvideo-table-container"><table class="table table-hover"><tbody>
			<?php $videos = $row->getVideos(); ?>
			<?php foreach($videos as $video) : ?>
				<tr>
					<td class="cell cell-id"><?= $video->getId() ?></td>
					<td class="cell"><?= $video->getFilename() ?></td>
					<td class="cell cell-ctrls">
						<?php
							$buttons = array();
							if(!empty($this->video_buttons)){
								foreach($this->video_buttons as $button){
									$routeParams = array(
										$this->parent_param_name => $this->parent_id,
										$this->edit_param_name => call_user_func(array($row, $idGetter)),
										$button['param_name'] => $video->getId(),
										'alias' => $this->parent_alias,
										$this->item_alias_name => $row->getAlias()
									);
									
									if(empty($button['more_params']))
										$button['more_params'] = array();
							
									$buttons[] = array(
										'title' => $button['title'],
										'route' => $button['route'],
										'params' => $button['more_params'] + $routeParams
									);
								}
							}
						?>
						<?php $c = 0;?>
						<?php foreach($buttons as $button): ?>
							<?= $c == 0 ? '' : '|'  ?>
							<a href="<?php echo $this->url($button['route'], $button['params']); ?>" <?= empty($button['warning']) ? '' : 'onclick=" return confirm(\''.$button['warning'].'\')"' ?> >
								<?php echo $this->translate($button['title']) ?>
							</a>
							<?php $c++; ?>
						<?php endforeach; ?>
					</td>
				</tr>
			<?php endforeach; ?>
		</tbody><tfoot><tr><td colspan="3"></td></tr></tfoot></table></td></tr>
    <?php endforeach; ?>
    </tbody>
    <tfoot>
    <tr>
        <td colspan="<?php echo count($this->columns) + 1; ?>">
            <?php echo $this->paginationControl($paginator, 'Sliding', 'partial/admin_pagination.phtml', array('list_route' => $this->list_route, 'parent_param_name' => $this->parent_param_name, 'parent_id' => $this->parent_id)); ?>
        </td>
    </tr>
    </tfoot>
</table>
